export const topNav = [
    {
        id:"0",
        name:"Home",
        path:"/",
    },
    {
        id:"1",
        name:"About",
        path:"/about",
    },
    {
        id:"2",
        name:"windowSpeech",
        path:"/windowSpeech",
    },
    {
        id:"3",
        name:"function",
        path:"/function",
    },
    {
        id:"4",
        name:"videoPlayer",
        path:"/video",
    },
    {
        id:"5",
        name:"point",
        path:"/point",
    },
    {
        id:"6",
        name:"tableDemo",
        path:"/tableSelect",
    },
    {
        id:"8",
        name:"mapPoint",
        path:"/mapPoint",
    },
    {
        id:"9",
        name:"canvasDemo",
        path:"/canvasDemo",
    },
    {
        id:"10",
        name:"countdown",
        path:"/countdown",
    },
]